CONFIG_ZMK_KEYBOARD_NAME="CorneLP"

# CONFIG_ZMK_EXT_POWER=y

# 1. Base Hardware Display Engine
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_SSD1306=y

# 2. Force Text-Based UI Over Graphics Engine
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n

# 3. Widgets Configuration
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# 4. Driver Utilities
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_STUDIO=y
